In [1]:
import numpy as ny
import pandas as ps
import matplotlib as ml
import seaborn as se

In [116]:
DF=ps.read_csv(r"C:\Users\ShinChan\Downloads\practice.csv")

In [6]:
DF.columns

Index(['MSSubClass', 'MSZoning', 'LotArea', 'LotShape', 'LotConfig',
       'LandSlope', 'OverallQual', 'YearBuilt', 'MasVnrArea', 'ExterQual',
       'BsmtExposure'],
      dtype='object')

In [7]:
DF.select_dtypes(include="object")

   MSZoning LotShape LotConfig LandSlope ExterQual BsmtExposure
0        RL      Reg    Inside       Gtl        Gd           No
1        RL      Reg       FR2       Gtl        TA           Gd
2        RL      IR1    Inside       Gtl        Gd           Mn
3        RL      IR1    Corner       Gtl        TA           No
4        RL      IR1       FR2       Gtl        Gd           Av
5        RL      IR1    Inside       Gtl        TA           No
6        RL      Reg    Inside       Gtl        Gd           Av
7        RL      IR1    Corner       Gtl        TA           Mn
8        RM      Reg    Inside       Gtl        TA           No
9        RL      Reg    Corner       Gtl        TA           No
10       RL      Reg    Inside       Gtl        TA           No
11       RL      IR1    Inside       Gtl        Ex           No
12       RL      IR2    Inside       Gtl        TA           No
13       RL      IR1    Inside       Gtl        Gd           Av
14       RL      IR1    Corner       Gtl        TA           No
15       RM      Reg    Corner       Gtl        TA           No
16       RL      IR1   CulDSac       Gtl        TA           No
17       RL      Reg    Inside       Gtl        TA          NaN
18       RL      Reg    Inside       Gtl        TA           No
19       RL      Reg    Inside       Gtl        TA           No
20       RL      IR1    Corner       Gtl        Gd           Av
21       RM      Reg    Inside       Gtl        TA           No
22       RL      Reg    Inside       Gtl        Gd           No
23       RM      Reg    Inside       Gtl        TA           No
24       RL      IR1    Inside       Gtl        TA           Mn
25       RL      Reg    Corner       Gtl        Gd           No
26       RL      Reg    Corner       Gtl        TA           Mn
27       RL      Reg    Inside       Gtl        Gd           No
28       RL      IR1   CulDSac       Gtl        TA           Gd
29       RM      IR1    Inside       Gtl        TA           No

In [125]:
DF.select_dtypes(exclude="object")

    MSSubClass  LotArea  OverallQual  YearBuilt  MasVnrArea
0           60     8450            7       2003         196
1           20     9600            6       1976           0
2           60    11250            7       2001         162
3           70     9550            7       1915           0
4           60    14260            8       2000         350
5           50    14115            5       1993           0
6           20    10084            8       2004         186
7           60    10382            7       1973         240
8           50     6120            7       1931           0
9          190     7420            5       1939           0
10          20    11200            5       1965           0
11          60    11924            9       2005         286
12          20    12968            5       1962           0
13          20    10652            7       2006         306
14          20    10920            6       1960         212
15          45     6120            7       1929           0
16          20    11241            6       1970         180
17          90    10791            4       1967           0
18          20    13695            5       2004           0
19          20     7560            5       1958           0
20          60    14215            8       2005         380
21          45     7449            7       1930           0
22          20     9742            8       2002         281
23         120     4224            5       1976           0
24          20     8246            5       1968           0
25          20    14230            8       2007         640
26          20     7200            5       1951           0
27          20    11478            8       2007         200
28          20    16321            5       1957           0
29          30     6324            4       1927           0

In [9]:
DF.shape

(30, 11)

In [10]:
DF.rename({"MSSubClass":"SubClass","MSZoning ":"Zones"})

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No

In [14]:
DF.MSZoning.value_counts()

RL    25
RM     5
Name: MSZoning, dtype: int64

In [15]:
DF.LotShape.value_counts()

Reg    16
IR1    13
IR2     1
Name: LotShape, dtype: int64

In [16]:
DF.LotConfig.value_counts()

Inside     18
Corner      8
CulDSac     2
FR2         2
Name: LotConfig, dtype: int64

In [17]:
DF.YearBuilt.max()

2007

In [18]:
DF.YearBuilt.min()

1915

In [20]:
DF["Year_diff"]=DF.YearBuilt.apply(lambda l:2020-l)

In [21]:
DF.tail(3)

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,Year_diff
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,13
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,63
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,93

In [25]:
DF.groupby(["MSZoning"])["OverallQual"].value_counts()

MSZoning  OverallQual
RL        5              9
          8              6
          7              5
          6              3
          4              1
          9              1
RM        7              3
          4              1
          5              1
Name: OverallQual, dtype: int64

In [28]:
DF.groupby(["MSZoning","OverallQual"]).get_group(("RM",7))

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,Year_diff
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,89
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,91
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,90

In [31]:
DF[DF["BsmtExposure"]=="Mn"]["LotArea"].max()

11250

In [61]:
DF.sort_values(by=["MSSubClass","YearBuilt"],ascending=[False,True])

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,Year_diff
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No,81
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No,44
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN,53
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No,105
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,47
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av,20
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,19
0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No,17
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No,15
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av,15
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,89
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No,27
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,91
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,90
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,93
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,69
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,63
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No,62
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No,60
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No,58
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No,55
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,52
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No,50
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd,44
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No,18
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av,16
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No,16
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av,14
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No,13
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,13

In [64]:
DF["OverallQual"].mean()

6.3

In [65]:
DF["OverallQual"].mode()

0    5
dtype: int64

In [66]:
DF["OverallQual"].median()

6.5

In [76]:
DF.groupby(["YearBuilt"])["OverallQual"].max()

YearBuilt
1915    7
1927    4
1929    7
1930    7
1931    7
1939    5
1951    5
1957    5
1958    5
1960    6
1962    5
1965    5
1967    4
1968    5
1970    6
1973    7
1976    6
1993    5
2000    8
2001    7
2002    8
2003    7
2004    8
2005    9
2006    7
2007    8
Name: OverallQual, dtype: int64

In [84]:
DF.to_csv(r"C:\Users\ShinChan\Downloads\data_1.csv")

In [85]:
ps.read_csv(r"C:\Users\ShinChan\Downloads\data_1.csv")

,Unnamed: 0,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure,Year_diff
0,0,60,RL,8450,Reg,Inside,Gtl,7,2003,196,Gd,No,17
1,1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,TA,Gd,44
2,2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn,19
3,3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,TA,No,105
4,4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Gd,Av,20
5,5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No,27
6,6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av,16
7,7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,TA,Mn,47
8,8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No,89
9,9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,TA,No,81
10,10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No,55
11,11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No,15
12,12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No,58
13,13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av,14
14,14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,TA,No,60
15,15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,TA,No,91
16,16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,TA,No,50
17,17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN,53
18,18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No,16
19,19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No,62
20,20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Gd,Av,15
21,21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No,90
22,22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No,18
23,23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No,44
24,24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn,52
25,25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,Gd,No,13
26,26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,TA,Mn,69
27,27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No,13
28,28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,TA,Gd,63
29,29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No,93

In [97]:
nu=DF.LotArea

In [98]:
DF["nu"]=nu

In [102]:
DF.MasVnrArea.replace({0:-1},inplace=True)

In [106]:
DF[DF["MasVnrArea"]==0]

Empty DataFrame
Columns: [MSSubClass, MSZoning, LotArea, LotShape, LotConfig, LandSlope, OverallQual, YearBuilt, MasVnrArea, ExterQual, BsmtExposure, Year_diff, nu]
Index: []

In [127]:
DF["MSZoning"][0]="NaN"

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [132]:
DF.isnull().count()

MSSubClass      30
MSZoning        30
LotArea         30
LotShape        30
LotConfig       30
LandSlope       30
OverallQual     30
YearBuilt       30
MasVnrArea      30
ExterQual       30
BsmtExposure    30
dtype: int64

In [128]:
DF["MSZoning"][0]

'NaN'

In [136]:
df=se.load_dataset("titanic")

In [134]:
se.get_dataset_names()

C:\ProgramData\Anaconda3\lib\site-packages\seaborn\utils.py:376: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 376 of the file C:\ProgramData\Anaconda3\lib\site-packages\seaborn\utils.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  gh_list = BeautifulSoup(http)

['anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'iris',
 'mpg',
 'planets',
 'tips',
 'titanic']

In [142]:
o=df.isnull()

In [150]:
o.replace({True:1,False:0},inplace=True)

In [159]:
o.deck.sum()

688

In [154]:
len(df.deck)

891

In [161]:
(o.sum()/len(df))*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [167]:
DF.drop(columns="ExterQual")

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,BsmtExposure
0,60,NaN,8450,Reg,Inside,Gtl,7,2003,196,No
1,20,RL,9600,Reg,FR2,Gtl,6,1976,0,Gd
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Mn
3,70,RL,9550,IR1,Corner,Gtl,7,1915,0,No
4,60,RL,14260,IR1,FR2,Gtl,8,2000,350,Av
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,No
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Av
7,60,RL,10382,IR1,Corner,Gtl,7,1973,240,Mn
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,No
9,190,RL,7420,Reg,Corner,Gtl,5,1939,0,No
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,No
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,No
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,No
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Av
14,20,RL,10920,IR1,Corner,Gtl,6,1960,212,No
15,45,RM,6120,Reg,Corner,Gtl,7,1929,0,No
16,20,RL,11241,IR1,CulDSac,Gtl,6,1970,180,No
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,NaN
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,No
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,No
20,60,RL,14215,IR1,Corner,Gtl,8,2005,380,Av
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,No
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,No
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,No
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,Mn
25,20,RL,14230,Reg,Corner,Gtl,8,2007,640,No
26,20,RL,7200,Reg,Corner,Gtl,5,1951,0,Mn
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,No
28,20,RL,16321,IR1,CulDSac,Gtl,5,1957,0,Gd
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,No

In [168]:
DF[DF["LotConfig"]=="Inside"]

,MSSubClass,MSZoning,LotArea,LotShape,LotConfig,LandSlope,OverallQual,YearBuilt,MasVnrArea,ExterQual,BsmtExposure
0,60,NaN,8450,Reg,Inside,Gtl,7,2003,196,Gd,No
2,60,RL,11250,IR1,Inside,Gtl,7,2001,162,Gd,Mn
5,50,RL,14115,IR1,Inside,Gtl,5,1993,0,TA,No
6,20,RL,10084,Reg,Inside,Gtl,8,2004,186,Gd,Av
8,50,RM,6120,Reg,Inside,Gtl,7,1931,0,TA,No
10,20,RL,11200,Reg,Inside,Gtl,5,1965,0,TA,No
11,60,RL,11924,IR1,Inside,Gtl,9,2005,286,Ex,No
12,20,RL,12968,IR2,Inside,Gtl,5,1962,0,TA,No
13,20,RL,10652,IR1,Inside,Gtl,7,2006,306,Gd,Av
17,90,RL,10791,Reg,Inside,Gtl,4,1967,0,TA,NaN
18,20,RL,13695,Reg,Inside,Gtl,5,2004,0,TA,No
19,20,RL,7560,Reg,Inside,Gtl,5,1958,0,TA,No
21,45,RM,7449,Reg,Inside,Gtl,7,1930,0,TA,No
22,20,RL,9742,Reg,Inside,Gtl,8,2002,281,Gd,No
23,120,RM,4224,Reg,Inside,Gtl,5,1976,0,TA,No
24,20,RL,8246,IR1,Inside,Gtl,5,1968,0,TA,Mn
27,20,RL,11478,Reg,Inside,Gtl,8,2007,200,Gd,No
29,30,RM,6324,IR1,Inside,Gtl,4,1927,0,TA,No

In [169]:
DF.groupby(["LotShape"])["LotArea"].mean()

LotShape
IR1    11492.307692
IR2    12968.000000
Reg     9085.187500
Name: LotArea, dtype: float64